name: Run unit test of feature branches

on:
  push:
    branches:
      'feature/*'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
